apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmedia-deployment
  labels:
    app: socialmedia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socialmedia
  template:
    metadata:
      labels:
        app: socialmedia
    spec:
      containers:
        - name: socialmedia
          image: socialmedia:1.0   # local image (Docker Desktop shares the daemon with K8s)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:                # REQUIRED for HPA (CPU target)
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
