apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: project8
spec:
  replicas: 2
  selector:
    matchLabels: { app: auth }
  template:
    metadata:
      labels: { app: auth }
    spec:
      containers:
      - name: auth
        image: <your-dockerhub-username>/auth:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: project8-secrets
              key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: project8
spec:
  selector: { app: auth }
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
