apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: project8
spec:
  replicas: 2
  selector:
    matchLabels: { app: orders }
  template:
    metadata:
      labels: { app: orders }
    spec:
      containers:
      - name: orders
        image: <your-dockerhub-username>/orders:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: USERS_URL
          value: http://users:8081
        - name: PRODUCTS_URL
          value: http://products:8081
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: project8
spec:
  selector: { app: orders }
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
