apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: project8
spec:
  replicas: 2
  selector:
    matchLabels: { app: products }
  template:
    metadata:
      labels: { app: products }
    spec:
      containers:
      - name: products
        image: <your-dockerhub-username>/products:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: mongo
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: project8
spec:
  selector: { app: products }
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
