apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: project8
spec:
  replicas: 2
  selector:
    matchLabels: { app: users }
  template:
    metadata:
      labels: { app: users }
    spec:
      containers:
      - name: users
        image: <your-dockerhub-username>/users:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: AUTH_URL
          value: http://auth:8081
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: project8
spec:
  selector: { app: users }
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
