apiVersion: v1
kind: Service
metadata:
  name: socialmedia-service
spec:
  type: NodePort
  selector:
    app: socialmedia
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080   # you’ll reach it at http://localhost:30080
